server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    mappings:
      enabled: true


spring:
  datasource:
    url: jdbc:h2:file:./Application/db-files/data
    driverClassName: org.h2.Driver
    username: "admin"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true