server:
  port: 8080
  error:
    include-message: "always"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    mappings:
      enabled: true


spring:
  datasource:
    url: jdbc:h2:file:./db-files/data
    driverClassName: org.h2.Driver
    username: "admin"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  cloud:
    azure:
      cosmos:
        endpoint: https://csg-weu-stg-dmota-3-sm-cosmos.documents.azure.com:443/
        database: servicemanagement-db
        key: ${COSMOSDB_KEY}
        client:
          connection-mode: DIRECT

